### ISSUE TITLE
iproute2 missing

### ISSUE THREAD

**Issue by fhufenreuter** [geerlingguy/docker-ubuntu1804-ansible#5]
I would like to test my roles with your image and need ansible_default_ipv4 to be available. Right now your image is missing iproute2 could you please add this package?

Thx

**Comment by maxbachmann** [comment]
I have the same problem with your ubuntu 1804 and 1604 docker image

**Comment by fhufenreuter** [comment]
Hi,

you can overcome this with the following pre tasks in your playbook.yml:
```
pre_tasks:
    - name: Ensure test dependencies are installed (RedHat).
      package: name=iproute state=present
      when: ansible_os_family == 'RedHat'
    - name: Ensure test dependencies are installed (Debian).
      package: name=iproute2 state=present
      when: ansible_os_family == 'Debian'
```
